### ISSUE TITLE
Are only Nordic nRF52840 supported right now?

### ISSUE THREAD

**Issue by vdbrink** [ffenix113/zigbee_home#10]
Can I buy any nRF52840 developer board (on Aliexpress) or is for now only the Nordic nRF52840 supported?

**Comment by ffenix113** [comment]
Hello vdbrink,

For now it is only for nRF52840 Dongle. I am working on MCUboot support to allow for other boards to be supported, but it is not ready yet.

**Comment by Hedda** [comment]
FYI, if you can not find the original from Nordic Semi then know that are many clones of the nRF52840 Dongle from third-parties that are probably pin-compatible
